
<?php 
	$previous = array(
	'Login/Register' => 'user/login'
	);
	$this->load->view("user_controls/breadcrumbs",Array("previous"=>$previous,"current"=>'Terms/Conditions'))?>
	
	
<div class="container">
	<div class="row">
		
		<div class="col-xs-12">
			<h2 class="title">Terms And Conditions</h2>
			<div>
				<strong>1. ACCEPTANCE OF TERMS</strong>
				<br>Welcome to www.askahgong.com. AskAhGong ("we" and "us", as the case may be) provides the Services including the use of this website(as defined below) to you, subject to the following Terms of Use, which may be updated by us in our sole discretion from time to time with or without notice to you. You are deemed to have been apprised of and bound by any changes to the Terms of Use. You agree that your continued use of the Service after such update will constitute your acceptance of and agreement to be bound by the updated Terms of Use. In addition, when using the Services or the website, you shall be subject to any posted guidelines or rules applicable to such services, which may be posted from time to time. All such guidelines or rules are hereby incorporated by reference into the Terms of Use. In most cases the guidelines and rules are specific to a particular part of the Service and will assist you in applying the Terms of Use to that part, but to the extent of any inconsistency between the Terms of Use and any guideline or rule, the Terms of Use will prevail.
				<br><br><strong>2. DESCRIPTION OF SERVICE</strong>
				<br>We provide users with access and use of materials or Contents on askahgong.com through our network of properties which may be accessed through any various medium or device now known or hereafter developed, including but not limited to the World Wide Web. You also understand and agree that the Service may include certain communications from us, such as service announcements, administrative messages and newsletters. Unless explicitly stated otherwise, any new features that augment or enhance the current Service shall be subject to the Terms of Use. You understand and agree that the Service is provided on an "AS-IS" basis and that we assume no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalisation settings. You are responsible for obtaining access to the Service, and that access may involve third-party fees (such as Internet service provider or airtime charges). You are responsible for those fees, including those fees associated with the display or delivery of advertisements. In addition, you must provide and are responsible for all equipment necessary to access the Service. Unless expressly stated otherwise, no information presented in the Service or in connection with any products and services forming part of the Service shall be deemed as a binding offer by us or the relevant third party, but may constitute an invitation for you to place an order. In respect of contracts for our or any third party's products and services which are made available as part of the Service, these shall be deemed concluded when we or the relevant third party have accepted your order for the same or have provided you with the product or service pursuant to your order.
				<br><br><strong>3. YOUR REGISTRATION OBLIGATIONS</strong>
				<br>In consideration of your use of the Service, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of Malaysia or other applicable jurisdiction. You also agree to: (a) provide true, accurate, current and complete information about yourself and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, we reserve the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof). We may provide you with access to some parts of the Service without you registering as a user.
				<br><br><strong>4. PRIVACY</strong>
				<br>By giving or making available the Registration Data and such other information about yourself to us, you agree and acknowledge that we may use or release such information to third parties and that you give consent to such use or disclosure. You further agree that providing us with your Registration Data and/or using the Service, you expressly request to receive and consent to receiving communications and materials from us from time to time. You understand that through your use of the Service you consent to the collection and use of this information, including the transfer of this information to other countries for storage, processing and use by us and our affiliates.
				<br><br><strong> 5. CONDUCT</strong>
				<br>You understand that all Content, whether publicly posted or privately transmitted, are the sole responsibility of the person from whom such Content originated. This means that you are entirely responsible for all Content that you upload, post, email, transmit or otherwise make available via the Service. We bear no responsibility for the Content posted via the Service and, as such, do not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Service, you may be exposed to Content that may be construed or regarded as offensive, indecent, fraudulent, objectionable, inaccurate, defamatory or erroneous. Under no circumstances will we or our licensors, suppliers, vendors, parent, holding, subsidiary or related companies, affiliates, officers, agents or employees, as the case may be, be liable in any way for any Content, including, but not limited to, any exposure to offensive, indecent, fraudulent, defamatory or objectionable Content, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of any Content posted, emailed, transmitted or otherwise made available via the Service. You agree to not use the Service to: 
				
				<br>(a) upload, post, email, transmit or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, pornographic, libelous, invasive of another's privacy, subversive, hateful, or racially, ethnically or otherwise objectionable or contrary to public interest, public order or national harmony in all relevant jurisdictions; 
				<br>(b) harm minors in any way; 
				<br>(c) impersonate any person or entity, including, but not limited to, our servant, agent, employee or official, forum leader, guide or host, or falsely state or otherwise misrepresent your affiliation with a person or entity; 
				<br>(d) forge headers or otherwise manipulate identifiers in order to disguise the origin of any Content transmitted through the Service; 
				<br>(e) upload, post, email, transmit or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements); 
				<br>(f) upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights of any party; 
				<br>(g) upload, post, email, transmit or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation, except in those areas that are designated for such purpose; 
				<br>(h) upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; 
				<br>(i) disrupt the normal flow of dialogue, cause a screen to "scroll" faster than other users of the Service are able to type, or otherwise act in a manner that negatively affects other users' ability to engage in real time exchanges; 
				<br>(j) interfere with or disrupt the Service or another person's use of the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service;
				 <br>(k) intentionally or unintentionally violate any applicable law, statute, ordinance, regulation, rule or code, including, but not limited to, any regulations, rules, notices, instructions or directives of any regulatory body or authority, governmental agency or national or other securities exchange ; 
				<br>(l) "stalk" or otherwise harass another; 
				<br>(m) commit any fraudulent or unlawful act, whether in relation to any third party provider of products and services on the Service or otherwise and/or 
				<br>(n) collect or store personal data about other users in connection with the prohibited conduct and activities set forth in paragraphs above. 
				<br>(o) to cache, hyperlink to, and frame the whole or any part of any websites comprised of in the Service save with our prior written permission.
				<br>We reserve all our rights to disable any links to any other website in our sole absolute discretion. You acknowledge that we may or may not pre-screen Content, but that we and our designees shall have the right (but not the obligation) in their sole discretion to pre-screen, refuse, move or remove any Content that is available via the Service. Without limiting the foregoing, we and our designees shall have the right to remove any Content (whether or not provided by you) that we believe in good faith violates the Terms of Use or that has been alleged to infringe any intellectual property or that is otherwise objectionable in our sole opinion, without being liable to you in any way for any loss or damage arising from such removal. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Content created by us or submitted to us, including without limitation information in all parts of the Service. You acknowledge, consent and agree that we may in our sole discretion access, preserve and disclose your account information and Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to: (a) comply with legal process; (b) enforce the Terms of Use; (c) respond to claims that any Content violates the rights of third parties; (d) respond to your requests for customer service; or (e) protect our rights, property or personal safety as well as those of our users and the public. You understand that the technical processing and transmission of the Service, including your Content, may involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. You understand that the Service and software embodied within the Service may include security components that permit digital materials to be protected, and that use of these materials is subject to usage rules set by us and our content providers who provide content to the Service. You may not attempt to override or circumvent any of the usage rules embedded into the Service. Any unauthorized reproduction, publication, further distribution or public exhibition of the materials provided on the Service, in whole or in part, is strictly prohibited.
				<br><br><strong>6. SPECIAL ADMONITIONS FOR INTERNATIONAL USE</strong>
				<br>Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. Specifically, you agree to comply with all applicable laws regarding the transmission of technical data exported from the country in which you reside.
				<br><br><strong>7. CONTENT SUBMITTED OR MADE AVAILABLE FOR INCLUSION ON THE SERVICE</strong>
				<br>With regard to the Contents which you submit or make available for inclusion on the Service, you agree to grant us and we hereby accept a worldwide, perpetual, irrevocable, sub-licensable, royalty-free, transferable and exclusive license(s), to use, distribute, reproduce, modify, adapt, publish, broadcast, translate, publicly perform and publicly display such Content (in whole or in part) and to incorporate such Content into other works in print and/or in any other format or medium now known or later developed.
				<br>In this connection, Content includes the following non-exhaustive items: information, data, text, software, music, sound, photographs, graphics, video, messages, tags, links or other materials.
				<br><br><strong>8. CONTRIBUTIONS</strong>
				<br>By submitting ideas, suggestions, documents, and/or proposals ("Contributions") to us, you acknowledge and agree that: (a) your Contributions do not contain confidential or proprietary information; (b) we are not under any obligation of confidentiality, express or implied, with respect to the Contributions; (c) we shall be entitled to use or disclose (or choose not to use or disclose) such Contributions for any purpose, in any way, in any media worldwide; (d) we may have something similar to the Contributions already under consideration or in development; (e) your Contributions automatically become our property without any obligation on our part to you; and (f) you are not entitled to any compensation or reimbursement of any kind from us under any circumstances.
				<br><br><strong>9. INDEMNITY</strong>
				<br>You agree to indemnify and hold us and our parent, holding, subsidiary, affiliated and related companies, officers, agents, employees, partners, suppliers, vendors, co-branders, licensors harmless from any claim or demand, including reasonable legal or attorneys' fees, made by any third party due to or arising out of Content you submit, post, transmit or otherwise make available through the Service, your use of the Service, your connection to the Service, your violation of the Terms of Use, or your violation of any rights of another or your breach of any applicable law.
				<br><br><strong>10. NO RESALE OF SERVICE</strong>
				<br>You agree not to reproduce, duplicate, copy, sell, trade, resell or exploit for any commercial purposes, any portion of the Service, use of the Service, or access to the Service including all Content such as photographs, advertisements, information, listings and articles whether posted by others or by yourself.
				<br><br><strong>11. GENERAL PRACTICES REGARDING USE AND STORAGE</strong>
				<br>You acknowledge that we may, in its sole discretion, establish general practices and limits concerning use of the Service, including without limitation the manner in which the Service is used, the maximum number of days that email messages, message board postings or other uploaded Content will be retained by the Service, the maximum number of email messages that may be sent from or received by an account on the Service, the maximum size of any email message that may be sent from or received by an account on the Service, the maximum disk space that will be allotted on our servers on your behalf, and the maximum number of times (and the maximum duration for which) you may access the Service in a given period of time. In particular, but without limiting the foregoing, by using the Service, you hereby consent to our adoption of the practices as set forth herein in relation to your use of the Service. You agree that we have no responsibility or liability for the deletion or failure to store any messages and other communications or other Content maintained or transmitted by or made available through the Service. You acknowledge that we reserve the right to log off accounts that are inactive for an extended period of time. You further acknowledge that we reserve the right to modify these general practices and limits from time to time , in our sole discretion, with or without notice, and you agree that your continued use of the Service after such modification will constitute your acceptance of agreement to be bound by the modified general practices and limits.
				<br><br><strong>12. MODIFICATIONS TO SERVICE</strong>
				<br>We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that we shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.
				<br><br><strong>13. TERMINATION</strong>
				<br>You agree that we may, under certain circumstances and without prior notice, immediately terminate your account, any associated email address, and access to the Service. Cause for such termination shall include, but not be limited to, (a) breaches or violations or purported breaches or violations of the Terms of Use or other incorporated agreements or guidelines, (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), (d) discontinuance or material modification to the Service (or any part thereof), (e) unexpected technical or security issues or problems, (f) extended periods of inactivity, (g) engagement by you in fraudulent or illegal activities, and/or (h) nonpayment of any fees owed by you in connection with the Services. Termination of your account includes (a) removal of access to all offerings within the Service, (b) deletion of your password and all related information, files and content associated with or inside your account (or any part thereof), and (c) barring of further use of the Service. Further, you agree that all terminations for cause shall be made in our sole discretion and that we shall not be liable to you or any third party for any termination of your account, any associated email address, or access to the Service.
				<br><br><strong>14. DEALINGS WITH ADVERTISERS</strong>
				<br>The Service may also include access to products and services of independent third parties either directly or via links to sites operated by such third party advertisers. Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Service, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertisers, You agree that we shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Service.
				<br><br><strong>15. LINKS</strong>
				<br>The Service may provide, or third parties may provide, links to other World Wide Web sites or resources. Since we do not possess any control over such sites and resources, you acknowledge and agree that we will not be held responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any Content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.
				<br><br><strong>16. OUR PROPRIETARY RIGHTS</strong>
				<br>You acknowledge and agree that the Service and any necessary software used in connection with the Service ("Software") contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You further acknowledge and agree that Content contained in sponsor advertisements or information presented to you through the Service or by advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly authorised by us or our advertisers, you agree not to modify, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Software, in whole or in part. We grant you a personal, non-transferable and non-exclusive right and license to use the object code of its Software on a single computer; provided that you do not (and do not allow any third party to) copy, reproduce, modify, create a derivative work from, reverse engineer, reverse assemble or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in or otherwise transfer any right in the Service. You agree neither to modify the Software in any manner or form, nor to use modified versions of the Software, including (without limitation) for the purpose of obtaining unauthorized access to the Service. You agree not to access the Service by any means other than through the interface that is provided by us for use in accessing the Service.
				<br><br><strong>17. DISCLAIMER OF WARRANTIES</strong>
				<br>YOU EXPRESSLY UNDERSTAND AND AGREE THAT:
				<br>(a) YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE AND OUR PARENT, HOLDING, SUBSIDIARY AND RELATED COMPANIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, LICENSORS, SUPPLIERS AND VENDORS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT (OTHER THAN ANY WARRANTY THE EXCLUSION OF WHICH IS NOT LAWFUL).
				<br>(b) WE AND OUR PARENT, HOLDING, SUBSIDIARY AND RELATED COMPANIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS, LICENSORS, SUPPLIERS AND VENDORS MAKE NO WARRANTY THAT (i) THE SERVICE WILL MEET YOUR REQUIREMENTS; (ii) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (iii) THE SERVICE WILL BE ACCESSIBLE AT ANY TIME OR AT ALL TIMES VIA THE CHANNEL SELECTED OR USED BY YOU, (iv) THE INFORMATION, CONTENT OR ADVERTISEMENTS CONTAINED ON, DISTRIBUTED THROUGH, OR LINKED, DOWNLOADED OR ACCESSED FROM OR THROUGH THE SERVICE (THE "MATERIALS") OR THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE; (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS; AND (v) ANY ERRORS IN THE SERVICE WILL BE CORRECTED.
				<br>(c) ANY RELIANCE UPON OR USE OF ANY OF THE MATERIALS SHALL BE AT YOUR OWN DISCRETION AND RISK. WE RESERVE THE RIGHT, IN OUR SOLE DISCRETION AND WITHOUT ANY OBLIGATION, TO MAKE IMPROVEMENTS TO, OR CORRECT ANY ERROR OR OMISSIONS IN, ANY PART OF THE SERVICE OR THE MATERIALS. THE MATERIALS ARE PROVIDED OR MADE AVAILABLE BY US ON AN "AS IS" BASIS, AND WE EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO ANY OF THE MATERIALS OR THE PRODUCTS.
				<br>(d) ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR EQUIPMENT OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.
				<br>(e) NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US OR OUR LICENSORS, SUPPLIERS, VENDORS, PARENT, HOLDING, SUBSIDIARY OR RELATED COMPANIES, AFFILIATES, OFFICERS, AGENTS OR EMPLOYEES OR THROUGH OR FROM THE SERVICE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS OF USE (SAVE FOR ANY FRAUDULENT MISREPRESENTATION BY US OR OUR LICENSORS, SUPPLIERS, VENDORS, PARENT, HOLDING, SUBSIDIARY OR RELATED COMPANY, AFFILIATE, OFFICER, AGENT OR EMPLOYEE, AS THE CASE MAY BE).
				<br>(f) A SMALL PERCENTAGE OF USERS MAY EXPERIENCE EPILEPTIC SEIZURES WHEN EXPOSED TO CERTAIN LIGHT PATTERNS OR BACKGROUNDS ON A COMPUTER SCREEN OR WHILE USING THE SERVICE. CERTAIN CONDITIONS MAY INDUCE PREVIOUSLY UNDETECTED EPILEPTIC SYMPTOMS EVEN IN USERS WHO HAVE NO HISTORY OF PRIOR SEIZURES OR EPILEPSY. IF YOU, OR ANYONE IN YOUR FAMILY, HAVE AN EPILEPTIC CONDITION, CONSULT YOUR PHYSICIAN PRIOR TO USING THE SERVICE. IMMEDIATELY DISCONTINUE USE OF THE SERVICE AND CONSULT YOUR PHYSICIAN IF YOU EXPERIENCE ANY OF THE FOLLOWING SYMPTOMS WHILE USING THE SERVICE: DIZZINESS, ALTERED VISION, EYE OR MUSCLE TWITCHES, LOSS OF AWARENESS, DISORIENTATION, ANY INVOLUNTARY MOVEMENT, OR CONVULSIONS.
				<br><br><strong>18. LIMITATION OF LIABILITY</strong>
				<br>YOU EXPRESSLY UNDERSTAND AND AGREE THAT WE AND OUR PARENT, HOLDING, SUBSIDIARY AND RELATED COMPANIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF WE OR OUR LICENSORS, SUPPLIERS, VENDORS, PARENT, HOLDING, SUBSIDIARY OR RELATED COMPANY, AFFILIATE, OFFICER, AGENT OR EMPLOYEE, AS THE CASE MAY BE, HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (i) THE SERVICE, THE MATERIALS AND THE PRODUCTS; (ii) THE USE OR THE INABILITY TO USE THE SERVICE; (iii) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICE; (iv) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (v) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE; (vi) ANY GOODS OR SERVICES DISPOSED OF OR MESSAGES SENT OR RECEIVED USING THE SERVICE; OR (vii) ANY OTHER MATTER RELATING TO THE SERVICE, THE MATERIALS OR THE PRODUCTS. NOTHING IN THESE TERMS OF USE SHALL LIMIT THE LIABILITY OF US OR OUR LICENSORS, SUPPLIERS, VENDORS, PARENT, HOLDING, SUBSIDIARY OR RELATED COMPANIES, AFFILIATES, OFFICERS, AGENTS OR EMPLOYEES, AS THE CASE MAY BE FOR DEATH OR PERSONAL INJURY RESULTING FROM OUR OR THEIR NEGLIGENCE.
				<br><br><strong>19. EXCLUSIONS AND LIMITATIONS</strong>
				<br>YOU ACKNOWLEDGE THAT THE DISCLAIMERS AND EXCLUSIONS OF LIABILITY SET FORTH IN SECTIONS 18 AND 19 ABOVE REPRESENT A FAIR AND REASONABLE ALLOCATION OF THE RISKS AND BENEFITS OF THE AGREEMENT BETWEEN YOU AND US, TAKING ALL RELEVANT FACTORS INTO CONSIDERATION, INCLUDING WITHOUT LIMITATION THE VALUE OF THE CONSIDERATION PROVIDED BY YOU TO US AND THE AVAILABILITY AND COSTS OF INSURANCE WITH RESPECT TO THE SAID RISKS. YOU FURTHER AGREE THAT THESE DISCLAIMERS AND LIMITATIONS SHALL BE ENFORCEABLE TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.
				<br><br><strong>20. FINANCIAL MATTERS</strong>
				<br>The Service is provided for informational purposes only, and no Content included in the Service (such as any financial or calculation tools) is intended for trading or investing purposes nor shall it constitute any specific advice given to you. You agree that you are solely and absolutely responsible for all sale or investment decisions made by you. We and our licensors shall not be responsible or liable for the accuracy, usefulness or availability of any information transmitted or made available via the Service, and shall not be responsible or liable for any trading or investment decisions based on such information.
				<br><br><strong>21. THIRD-PARTY BENEFICIARIES</strong>
				<br>You agree that, except as otherwise expressly provided in this Terms of Use, there shall be no third-party beneficiaries to this agreement. You acknowledge that our licensors, suppliers, vendors, parent, holding, subsidiary and related companies, all affiliates, and our officers, agents and employees, are, where applicable, intended to be third party beneficiaries of any of the Terms herein. You also acknowledge that our co-branders and other partners are intended to be third party beneficiaries of Section 11. You agree that our licensors, suppliers, vendors, our parent, holding, subsidiary and related companies, all affiliates, our officers, agents and employees, and our co-branders and other partners may each enforce, severally and in its own right, any of the Terms herein as applicable, and the Singapore Contracts (Rights of Third Parties) Act (Cap. 53B) shall apply to the Terms of Use to the extent and in the manner set out or envisaged in the foregoing but to no further extent and in no other manner.
				<br><br><strong>22. NOTICE</strong>
				<br>We may provide you with notices, including those regarding changes to the Terms of Use, by email, regular mail or postings on the Service. You agree that such notices by email or regular mail, and such display of notices or links to notices to you generally on the Service, will constitute sufficient and adequate notice to you of the matters contained therein.
				<br><br><strong>23. TRADEMARK INFORMATION</strong>
				<br>The Askahgong logo, trademarks and service marks and other logos and product and service names are our trademarks and/or those of our licensors, suppliers, vendors, parent or holding company, as the case may be (the Marks"). Without the prior written permission of our licensor, supplier, vendor, parent or holding company or us, as the case may be, you agree not to display or use in any manner the Marks.
				<br><br><strong>24. GENERAL INFORMATION</strong>
				<br>Entire Agreement. The Terms of Use constitutes the entire agreement between you and us and governs your use of the Service, superseding any prior understandings, statements, representations and agreements between you and us with respect to the Service. For the avoidance of doubt, except to the extent provided in Section 22, you and we are the only parties to the Terms of Use. You also may be subject to additional terms and conditions that may apply when you use or purchase certain our other services, affiliate services, third-party content or third-party software.
				<br> Choice of Law and Forum. The Terms of Use and the relationship between you and us shall be governed by the laws of Malaysia without regard to its conflict of law provisions. Both you and we agree to submit to the non-exclusive jurisdiction of the courts of Malaysia.
				Waiver and Severability of Terms. The failure on our part to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of such right or provision. If any provision of the Terms of Use is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and to construe such provision to the maximum extent permitted by law so as to render that provision valid and enforceable, and the other provisions of the Terms of Use remain in full force and effect.
				No Right of Survivorship and Non-Transferability. You agree that your account with us is non-transferable and any rights to your ID or contents within your account shall terminate upon your death. Upon receipt of a copy of a death certificate, your account may be terminated and all contents therein permanently deleted.
				Statute of Limitations. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Service or the Terms of Use must be filed within one (1) year after such claim or cause of action arose or be forever barred.
				The section titles in the Terms of Use are for convenience only and have no legal or contractual effect.
				English version prevails. In the event that these Terms of Use are translated into other languages and there is a discrepancy between the two language versions, the English language version shall prevail to the extent that such discrepancy is the result of an error in translation.
				<br><br><strong>25. VIOLATIONS</strong>
				<br>Please report any violations of the Terms of Use to:
				<a href="mailto:ahgong@askahgong.com">ahgong@askahgong.com</a> 
	
	
	
			</div>
		</div>
		
		
	</div>
</div>
